### ISSUE TITLE
Overlap between polygons

### ISSUE THREAD

**Issue by angrypiggy** [cwfid/dataset#1]
Thank you for such an awesome dataset. One question is that, is there any overlap between the polygons labeled in the yaml annotation file? Thanks!

**Comment by angrypiggy** [comment]
It turned out that there are some overlaps. You can code to leave them unlabeled to avoid ambiguity.

**Comment by sebhaug** [comment]
Thanks for the question. It is described at the end of section 3.2 in the paper that if such overlap occurs between different classes the affected pixels shall be marked as invalid = unlabeled.
